# Generated by Django 3.0.3 on 2020-02-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0003_auto_20200219_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owned_cars',
            name='make',
            field=models.CharField(max_length=20),
        ),
    ]
