# Generated by Django 3.0.3 on 2020-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0004_auto_20200220_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='owned_cars',
            name='location',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
