# Generated by Django 3.0.3 on 2020-02-21 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rental_app', '0006_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='cars',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rental_app.owned_cars'),
            preserve_default=False,
        ),
    ]
